### ISSUE TITLE
Performing a _some query on a many relationship with no value raises an error

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone-5#1022]
In this case there is a `Program` which has been created without any `assignedAgents`. When I run the following query:

```gql
query userDashboard($userId: ID!) {
  allPrograms(where: {assignedAgents_some: {user: {id: $userId}}}) {
    id
  }
}
```

I get the following error:

```
{
  "errors": [
    {
      "message": "The argument to $size must be an array, but was of type: null",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "allPrograms"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "ok": 0,
          "errmsg": "The argument to $size must be an array, but was of type: null",
          "code": 17124,
          "codeName": "Location17124",
          "name": "MongoError",
          "stacktrace": [
            "MongoError: The argument to $size must be an array, but was of type: null",
            "    at Connection.<anonymous> (/Users/timleslie/src/enlitic/MAP/node_modules/mongodb-core/lib/connection/pool.js:443:61)",
            "    at Connection.emit (events.js:197:13)",
            "    at processMessage (/Users/timleslie/src/enlitic/MAP/node_modules/mongodb-core/lib/connection/connection.js:364:10)",
            "    at Socket.<anonymous> (/Users/timleslie/src/enlitic/MAP/node_modules/mongodb-core/lib/connection/connection.js:533:15)",
            "    at Socket.emit (events.js:197:13)",
            "    at addChunk (_stream_readable.js:288:12)",
            "    at readableAddChunk (_stream_readable.js:269:11)",
            "    at Socket.Readable.push (_stream_readable.js:224:10)",
            "    at TCP.onStreamRead [as onread] (internal/stream_base_commons.js:145:17)"
          ]
        }
      },
      "uid": "cjudn4w9f000oz9mf7itth0dw",
      "name": "GraphQLError"
    }
  ],
  "data": {
    "allPrograms": null
  },
  "extensions": {}
}
```

Adding a single `assignedAgent` to the `Program` allows the query to work as expected. Removing the `assignedAgent` again leaves the program in a state which doesn't cause an error, presumably because the relationship field now has a value of `[]` rather than `null`.

**Comment by timleslie** [comment]
Fixed in #1033
