### ISSUE TITLE
Running 'yarn build' crashes in demo blog

### ISSUE THREAD

**Issue by nathsimpson** [keystonejs/keystone-5#1226]
Running yarn build in the Keystone demo blog returns this error.

```
ℹ Command: keystone build
✔ Validated project entry file ./index.js
✔ Initialised Keystone instance
✖ Exporting Keystone build to ./dist
TypeError: build is not a function
    at NextApp.build (/Users/nathansimpson/Documents/GitHub/keystone-5/packages/app-next/index.js:22:12)
    at Promise.all.apps.map.app (/Users/nathansimpson/Documents/GitHub/keystone-5/packages/keystone/bin/commands/build.js:44:22)
    at Array.map (<anonymous>)
    at Object.exec (/Users/nathansimpson/Documents/GitHub/keystone-5/packages/keystone/bin/commands/build.js:43:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
➜  blog git:(master) 
```

**Comment by nathsimpson** [comment]
I've traced the issue to packages/app-next/index.js

**Comment by nathsimpson** [comment]
I've traced the issue to packages/app-next/index.js

**Comment by nathsimpson** [comment]
I've traced the issue to packages/app-next/index.js
```

**Comment by nathsimpson** [comment]
Forgive me for my inability to articulate my words to describe this stuff.

I've traced the issue to packages/app-next/index.js
```
  async build() {
    console.log('nextBuild', nextBuild)
    return nextBuild(this._dir)
  }
```
as next/dist/build exports the function as `exports.default = build`, tweaking the above to...
```
  async build() {
    console.log('nextBuild', nextBuild)
    return nextBuild.default(this._dir)
  }
```
...resolved the problem. I'm sure there is a neater way of doing this though.

**Comment by nathsimpson** [comment]
`const nextBuild = require('next/dist/build').default`
