### ISSUE TITLE
Running Blog Project - Post Connection Error

### ISSUE THREAD

**Issue by stunjiturner** [keystonejs/keystone-5#1231]
when I try to run demo on Mac Mojave, MongoDB Running 4.0.3

```
✖ Connecting to database
Error: Post connection error
    at /Users/stunjiturner/Downloads/Code/keystone-5/demo-projects/blog/node_modules/@keystone-alpha/utils/dist/utils.cjs.dev.js:72:21
    at async executeDefaultServer (/Users/stunjiturner/Downloads/Code/keystone-5/demo-projects/blog/node_modules/@keystone-alpha/keystone/bin/utils.js:108:3) {
  errors: {
    MongooseAdapter: Error: Post connection error
        at MongooseAdapter.connect (/Users/stunjiturner/Downloads/Code/keystone-5/demo-projects/blog/node_modules/@keystone-alpha/keystone/lib/adapters/index.js:31:23)
        at processTicksAndRejections (internal/process/task_queues.js:89:5)
        at async pReflect (/Users/stunjiturner/Downloads/Code/keystone-5/demo-projects/blog/node_modules/p-reflect/index.js:5:17)
        at async Promise.all (index 0)
        at async executeDefaultServer (/Users/stunjiturner/Downloads/Code/keystone-5/demo-projects/blog/node_modules/@keystone-alpha/keystone/bin/utils.js:108:3) {
      errors: [Array]
    }
  }
}
error Command failed with exit code 1.
```

**Comment by jesstelford** [comment]
Thanks for the report! Are your able to run any of the other demos?

- `demo-projects/todo`
- `demo-projects/meetup`

**Comment by stunjiturner** [comment]
I tried meetup as well, same error

**Comment by stunjiturner** [comment]
is there a fix to this error

**Comment by jesstelford** [comment]
Hey @stunjiturner, I've not had a chance to look into this particular issue yet.

You may be able to debug the issue yourself by placing a breakpoint on `packages/keystone/lib/adapters/index.js:31` then running with `NODE_OPTIONS=--inspect-brk`

**Comment by MadeByMike** [comment]
@stunjiturner did you find a solution to this? From the information available it looks it has failed to connect to mongo and it might be an issue with your local MongoDB installation or configuration.

**Comment by MadeByMike** [comment]
I'm closing this for now but happy to help if we can get some more info. Or if we can narrow this down to an issue within keystone - even better :)
