### ISSUE TITLE
Creating a new Apollo Server throws an error

### ISSUE THREAD

**Issue by jesstelford** [keystonejs/keystone-5#1340]
```
❯ npm init keystone-app my-ks-app && cd my-ks-app && yarn start

╦╔═ ╔═╗ ╦ ╦ ╔═╗ ╔╦╗ ╔═╗ ╔╗╔ ╔═╗  ╦ ╔═╗
╠╩╗ ║╣  ╚╦╝ ╚═╗  ║  ║ ║ ║║║ ║╣   ║ ╚═╗
╩ ╩ ╚═╝  ╩  ╚═╝  ╩  ╚═╝ ╝╚╝ ╚═╝ ╚╝ ╚═╝

  ✔ Check ./my-ks-app
  ✔ Create KeystoneJS Project
  ✔ Install dependencies with Yarn

🎉 KeystoneJS app created in ./my-ks-app

Get started:

cd ./my-ks-app
yarn start

Next steps:

- Edit ./my-ks-app/index.js to customize your app.
- Open the Admin UI
- Read the docs
- Star KeystoneJS on GitHub

yarn run v1.15.2
$ cross-env NODE_ENV=development DISABLE_LOGGING=true keystone
ℹ Command: keystone dev
✔ Validated project entry file ./index.js
✔ Keystone server listening on port 3000
✔ Initialised Keystone instance
✖ Connecting to database
TypeError: Cannot read property 'some' of undefined
    at typeDefs.some.typeDef (node_modules/apollo-server-core/dist/utils/isDirectiveDefined.js:9:57)
    at Array.some (<anonymous>)
    at Object.exports.isDirectiveDefined (node_modules/apollo-server-core/dist/utils/isDirectiveDefined.js:9:21)
    at new ApolloServerBase (node_modules/apollo-server-core/dist/ApolloServer.js:146:39)
    at new ApolloServer (node_modules/apollo-server-express/dist/ApolloServer.js:46:9)
    at createApolloServer (node_modules/@keystone-alpha/app-graphql/lib/apolloServer.js:145:18)
    at GraphQLApp.prepareMiddleware (node_modules/@keystone-alpha/app-graphql/index.js:46:20)
    at Promise.all.filter.map.app (node_modules/@keystone-alpha/keystone/lib/Keystone/index.js:434:17)
    at Array.map (<anonymous>)
    at Keystone.prepare (node_modules/@keystone-alpha/keystone/lib/Keystone/index.js:433:12)
    at executeDefaultServer (node_modules/@keystone-alpha/keystone/bin/utils.js:106:42)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

Looks like this bug is from Apollo: https://github.com/apollographql/apollo-server/issues/2921

We're returning strings here:
https://github.com/keystonejs/keystone-5/blob/5e56bc4d4754ca4242b8f1d4cb6b819873a3254e/packages/keystone/lib/Keystone/index.js#L152

Perhaps we should wrap them in `gql` calls where it's passed to Apollo here: https://github.com/keystonejs/keystone-5/blob/master/packages/app-graphql/lib/apolloServer.js#L149

**Comment by jesstelford** [comment]
Fix released in `@keystone-alpha/keystone@7.0.1`
