### ISSUE TITLE
Error: No executable schema named 'undefined' is available. Have you setup '@keystone-alpha/app-graphql'?

### ISSUE THREAD

**Issue by Nakzz** [keystonejs/keystone-5#1624]
I tried following the https://v5.keystonejs.com/keystone-alpha/auth-passport/#api guide to implementing an auth system, however, I am getting the following error and can't seem to figure out why I am getting the error.  

I have the latest version of keystone, auth-passport, app-graphql. 

```
UnhandledPromiseRejectionWarning: Error: No executable schema named 'undefined' is available. Have you setup '@keystone-alpha/app-graphql'?
    at Keystone.executeQuery (/home/ajmain/Desktop/breezy-CMS/node_modules/@keystone-alpha/keystone/lib/Keystone/index.js:189:11)
    at Strategy._ServiceStrategy [as _verify] (/home/ajmain/Desktop/breezy-CMS/node_modules/@keystone-alpha/auth-passport/lib/Passport.js:412:34)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:22954) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:22954) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{ TokenError: Bad Request
    at Strategy.OAuth2Strategy.parseErrorResponse (/home/ajmain/Desktop/breezy-CMS/node_modules/passport-oauth2/lib/strategy.js:358:12)
    at Strategy.OAuth2Strategy._createOAuthError (/home/ajmain/Desktop/breezy-CMS/node_modules/passport-oauth2/lib/strategy.js:405:16)
    at /home/ajmain/Desktop/breezy-CMS/node_modules/passport-oauth2/lib/strategy.js:175:45
    at /home/ajmain/Desktop/breezy-CMS/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/home/ajmain/Desktop/breezy-CMS/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/home/ajmain/Desktop/breezy-CMS/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
  name: 'TokenError',
  message: 'Bad Request',
  code: 'invalid_grant',
  uri: undefined,
  status: 500 }
```

**Comment by MadeByMike** [comment]
@Nakzz I don't seem to be able to access that repository.

It seems like this might be a general support question\request? If so it might be better to point you to our community Slack channel: http://community.keystonejs.com/ You will find an answer here much faster.

If we find a specific bug with either passport of graphQL we can raise a new issue.
