### ISSUE TITLE
mocha 6.0.2 causes cypress tests to break

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone-5#833]
```
#!/bin/bash -eo pipefail
CYPRESS_CACHE_FOLDER=$CIRCLE_WORKING_DIRECTORY/node_modules/cypress/.cache/ bolt ws run cypress:run:ci --only-fs $PROJECT_DIRECTORY
⚡️   bolt v0.22.6 (node v8.15.1)
$ NODE_ENV=test DISABLE_LOGGING=true node -r dotenv-safe/config -e 'require(`execa`)(`start-server-and-test`, [`start`, `http-get://localhost:${process.env.PORT}/admin`, process.argv[1]], { stdio: `inherit` }).catch(error => { console.error(error.toString()); process.exit(error.code) })' cypress:run:cmd
starting server using command "npm run start"
and when url "http-get://localhost:3000/admin" is responding
running tests using command "cypress:run:cmd"

> @keystone-alpha/cypress-project-basic@1.0.1 start /home/circleci/repo/test-projects/basic
> node -r dotenv-safe/config `yarn bin`/keystone | sed -l -e 's/:\s*undefined\s*,/:null,/g' | tee out.log | pino-colada


> @keystone-alpha/cypress-project-basic@1.0.1 cypress:run:cmd /home/circleci/repo/test-projects/basic
> node -r dotenv-safe/config `which cypress` run

It looks like this is your first time using Cypress: 3.1.5

[22:43:14]  Verifying Cypress can run /home/circleci/repo/node_modules/cypress/.cache/3.1.5/Cypress [started]
[22:43:16]  Verifying Cypress can run /home/circleci/repo/node_modules/cypress/.cache/3.1.5/Cypress [completed]

Opening Cypress...

====================================================================================================

  (Run Starting)

  ┌────────────────────────────────────────────────────────────────────────────────────────────────┐
  │ Cypress:    3.1.5                                                                              │
  │ Browser:    Electron 59 (headless)                                                             │
  │ Specs:      14 found (add-edit-delete-data.js, columns_spec.js, create-buttons_spec.js, dateT… │
  └────────────────────────────────────────────────────────────────────────────────────────────────┘


────────────────────────────────────────────────────────────────────────────────────────────────────
                                                                                                    
  Running: add-edit-delete-data.js...                                                     (1 of 14) 

․․․․․․․․․․․

TypeError: Cannot read property 'passes' of undefined
    at Dot.Base.epilogue (/home/circleci/repo/node_modules/mocha/lib/reporters/base.js:318:25)
    at Runner.<anonymous> (/home/circleci/repo/node_modules/mocha/lib/reporters/dot.js:71:10)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:120:20)
    at Runner.emit (events.js:210:7)
    at Reporter.emit (/home/circleci/repo/node_modules/cypress/.cache/3.1.5/Cypress/resources/app/packages/server/lib/reporter.js:239:55)
    at Object.server.startWebsockets.onMocha (/home/circleci/repo/node_modules/cypress/.cache/3.1.5/Cypress/resources/app/packages/server/lib/project.js:296:22)
    at Socket.<anonymous> (/home/circleci/repo/node_modules/cypress/.cache/3.1.5/Cypress/resources/app/packages/server/lib/socket.js:237:36)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at /home/circleci/repo/node_modules/cypress/.cache/3.1.5/Cypress/resources/app/packages/socket/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)

TypeError: Cannot read property 'passes' of undefined
    at Dot.Base.epilogue (/home/circleci/repo/node_modules/mocha/lib/reporters/base.js:318:25)
    at Runner.<anonymous> (/home/circleci/repo/node_modules/mocha/lib/reporters/dot.js:71:10)
    at Object.onceWrapper (events.js:316:30)
    at emitOne (events.js:120:20)
    at Runner.emit (events.js:210:7)
    at Reporter.emit (/home/circleci/repo/node_modules/cypress/.cache/3.1.5/Cypress/resources/app/packages/server/lib/reporter.js:239:55)
    at Object.server.startWebsockets.onMocha (/home/circleci/repo/node_modules/cypress/.cache/3.1.5/Cypress/resources/app/packages/server/lib/project.js:296:22)
    at Socket.<anonymous> (/home/circleci/repo/node_modules/cypress/.cache/3.1.5/Cypress/resources/app/packages/server/lib/socket.js:237:36)
    at emitTwo (events.js:125:13)
    at Socket.emit (events.js:213:7)
    at /home/circleci/repo/node_modules/cypress/.cache/3.1.5/Cypress/resources/app/packages/socket/node_modules/socket.io/lib/socket.js:503:12
    at _combinedTickCallback (internal/process/next_tick.js:131:7)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by MadeByMike** [comment]
This issue is old and not currently an issues effecting the project. Both Cypress and Mocha have new versions and this will be discoverable if\when we attempt to upgrade.
