### ISSUE TITLE
Fix flakey knex test on CI

### ISSUE THREAD

**Issue by timleslie** [keystonejs/keystone-5#853]
The unit tests sometimes fail with the following error. It's a big blocker to momentum and we should solve this issue ASAP.

```
Summary of all failing tests
 FAIL  api-tests/queries/relationships.test.js
  ● Adapter: knex › Querying with relationship filters › to-many › _some condition

    expect(received).toContainEqual(expected) // deep equality

    Expected value: {"feed": [{"title": "Hello"}, {"title": "Just in time"}], "id": "1"}
    Received array: [{"feed": [{"title": "Just in time"}, {"title": "Hello"}], "id": "1"}, {"feed": [{"title": "I like Jelly"}], "id": "2"}]

      196 | 
      197 |             // We don't know the order, so we have to check individually
    > 198 |             expect(allUsers).toContainEqual({
          |                              ^
      199 |               id: users[0].id,
      200 |               feed: [{ title: 'Hello' }, { title: 'Just in time' }],
      201 |             });

      at toContainEqual (api-tests/queries/relationships.test.js:198:30)
```

**Comment by molomby** [comment]
It's an ordering issue, yes? The test relies on the items coming out of the DB in the order the `create` invocations are fired, eg..

```js
const posts = await Promise.all([
  create('Post', { title: 'Hello' }),
  create('Post', { title: 'Just in time' }),
  create('Post', { title: 'Bye' }),
  create('Post', { title: 'I like Jelly' }),
]);
```

One solution would be to reduce over the `create` array, resolving the promises in series, but this still relies on non-guaranteed behaviour (that records have a natural order, derived from their create order, and will, by default, be returned in that natural order).

A better solution is probably to explicitly order the results [as we do in other tests](https://github.com/keystonejs/keystone-5/blob/master/packages/fields/src/types/Text/filterTests.js#L17).

**Comment by molomby** [comment]
I've also seen this...

```
 FAIL  api-tests/relationships/nested-mutations/two-way-backreference/to-many.test.js
  ● Adapter: knex › update many to many relationship back reference › nested create › during create mutation

    expect(received).toMatchObject(expected)

    Expected value to match object:
      ["1", "2"]
    Received:
      ["2", "1"]

      at api-tests/relationships/nested-mutations/two-way-backreference/to-many.test.js:163:46
```

**Comment by MadeByMike** [comment]
Checked with @timleslie gone
